package pojoSigade;
// Generated May 3, 2017 3:42:48 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cierre generated by hbm2java
 */
@Entity
@Table(name = "cierre", catalog = "sigade")
public class Cierre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4689077242755281779L;
	private CierreId id;

	public Cierre() {
	}

	public Cierre(CierreId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ejercicioFiscal", column = @Column(name = "ejercicio_fiscal")),
			@AttributeOverride(name = "mesDesembolso", column = @Column(name = "mes_desembolso")),
			@AttributeOverride(name = "fechaCorte", column = @Column(name = "fecha_corte", length = 19)),
			@AttributeOverride(name = "codigoPresupuestario", column = @Column(name = "codigo_presupuestario", length = 45)),
			@AttributeOverride(name = "entidadCicoin", column = @Column(name = "entidad_cicoin")),
			@AttributeOverride(name = "unidadEjecutoraSicoin", column = @Column(name = "unidad_ejecutora_sicoin")),
			@AttributeOverride(name = "desembolsosUsd", column = @Column(name = "desembolsos_usd", precision = 15)),
			@AttributeOverride(name = "tcFechaCorte", column = @Column(name = "tc_fecha_corte")),
			@AttributeOverride(name = "desembolsosGtq", column = @Column(name = "desembolsos_gtq", precision = 15)) })
	public CierreId getId() {
		return this.id;
	}

	public void setId(CierreId id) {
		this.id = id;
	}

}
