package pojoSigade;
// Generated May 3, 2017 3:42:48 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Det generated by hbm2java
 */
@Entity
@Table(name = "det", catalog = "sigade")
public class Det implements java.io.Serializable {

	private DetId id;

	public Det() {
	}

	public Det(DetId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ejercicioFiscal", column = @Column(name = "ejercicio_fiscal")),
			@AttributeOverride(name = "mesDesembolso", column = @Column(name = "mes_desembolso", length = 2)),
			@AttributeOverride(name = "codigoPrespuestario", column = @Column(name = "codigo_prespuestario", length = 45)),
			@AttributeOverride(name = "etnidadSicoin", column = @Column(name = "etnidad_sicoin")),
			@AttributeOverride(name = "unidadEjecutoriaSicoin", column = @Column(name = "unidad_ejecutoria_sicoin")),
			@AttributeOverride(name = "monedaDesembolso", column = @Column(name = "moneda_desembolso", length = 45)),
			@AttributeOverride(name = "desembolsosMesMoneda", column = @Column(name = "desembolsos_mes_moneda", precision = 15)),
			@AttributeOverride(name = "tcMonUsd", column = @Column(name = "tc_mon_usd")),
			@AttributeOverride(name = "desembolsosMesUsd", column = @Column(name = "desembolsos_mes_usd", precision = 15)),
			@AttributeOverride(name = "tcUsdGtq", column = @Column(name = "tc_usd_gtq")),
			@AttributeOverride(name = "desembolsosMesGtq", column = @Column(name = "desembolsos_mes_gtq", precision = 15)) })
	public DetId getId() {
		return this.id;
	}

	public void setId(DetId id) {
		this.id = id;
	}

}
