package pojoSigade;
// Generated May 16, 2017 12:50:34 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DtmAvanceFisfinanDetDti generated by hbm2java
 */
@Entity
@Table(name = "DTM_AVANCE_FISFINAN_DET_DTI", schema = "DATAMART")
public class DtmAvanceFisfinanDetDti implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4154430372636848586L;
	private DtmAvanceFisfinanDetDtiId id;

	public DtmAvanceFisfinanDetDti() {
	}

	public DtmAvanceFisfinanDetDti(DtmAvanceFisfinanDetDtiId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ejercicioFiscal", column = @Column(name = "EJERCICIO_FISCAL", precision = 22, scale = 0)),
			@AttributeOverride(name = "mesDesembolso", column = @Column(name = "MES_DESEMBOLSO", nullable = false, length = 2)),
			@AttributeOverride(name = "codigoPresupuestario", column = @Column(name = "CODIGO_PRESUPUESTARIO", nullable = false, length = 12)),
			@AttributeOverride(name = "entidadSicoin", column = @Column(name = "ENTIDAD_SICOIN", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "unidadEjecutoraSicoin", column = @Column(name = "UNIDAD_EJECUTORA_SICOIN", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "monedaDesembolso", column = @Column(name = "MONEDA_DESEMBOLSO", nullable = false, length = 3)),
			@AttributeOverride(name = "desembolsosMesMoneda", column = @Column(name = "DESEMBOLSOS_MES_MONEDA", nullable = false, precision = 15, scale = 3)),
			@AttributeOverride(name = "tcMonUsd", column = @Column(name = "TC_MON_USD", nullable = false, precision = 27, scale = 20)),
			@AttributeOverride(name = "desembolsosMesUsd", column = @Column(name = "DESEMBOLSOS_MES_USD", nullable = false, precision = 15, scale = 3)),
			@AttributeOverride(name = "tcUsdGtq", column = @Column(name = "TC_USD_GTQ", nullable = false, precision = 27, scale = 20)),
			@AttributeOverride(name = "desembolsosMesGtq", column = @Column(name = "DESEMBOLSOS_MES_GTQ", nullable = false, precision = 15, scale = 3)) })
	public DtmAvanceFisfinanDetDtiId getId() {
		return this.id;
	}

	public void setId(DtmAvanceFisfinanDetDtiId id) {
		this.id = id;
	}

}
