package pojoSigade;
// Generated May 16, 2017 12:50:34 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DtmAvanceFisfinanCierreDti generated by hbm2java
 */
@Entity
@Table(name = "DTM_AVANCE_FISFINAN_CIERRE_DTI", schema = "DATAMART")
public class DtmAvanceFisfinanCierreDti implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1882235128234436042L;
	private DtmAvanceFisfinanCierreDtiId id;

	public DtmAvanceFisfinanCierreDti() {
	}

	public DtmAvanceFisfinanCierreDti(DtmAvanceFisfinanCierreDtiId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ejercicioFiscal", column = @Column(name = "EJERCICIO_FISCAL", precision = 22, scale = 0)),
			@AttributeOverride(name = "mesDesembolso", column = @Column(name = "MES_DESEMBOLSO", nullable = false, length = 2)),
			@AttributeOverride(name = "fechaCorte", column = @Column(name = "FECHA_CORTE", length = 7)),
			@AttributeOverride(name = "codigoPresupuestario", column = @Column(name = "CODIGO_PRESUPUESTARIO", nullable = false, length = 12)),
			@AttributeOverride(name = "entidadSicoin", column = @Column(name = "ENTIDAD_SICOIN", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "unidadEjecutoraSicoin", column = @Column(name = "UNIDAD_EJECUTORA_SICOIN", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "desembolsosUsd", column = @Column(name = "DESEMBOLSOS_USD", nullable = false, precision = 15, scale = 3)),
			@AttributeOverride(name = "tcFechaCorte", column = @Column(name = "TC_FECHA_CORTE", nullable = false, precision = 27, scale = 20)),
			@AttributeOverride(name = "desembolsosGtq", column = @Column(name = "DESEMBOLSOS_GTQ", nullable = false, precision = 15, scale = 3)) })
	public DtmAvanceFisfinanCierreDtiId getId() {
		return this.id;
	}

	public void setId(DtmAvanceFisfinanCierreDtiId id) {
		this.id = id;
	}

}
