package pojoSigade;
// Generated May 16, 2017 12:50:34 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DtmAvanceFisfinanOrgDti generated by hbm2java
 */
@Entity
@Table(name = "DTM_AVANCE_FISFINAN_ORG_DTI", schema = "DATAMART")
public class DtmAvanceFisfinanOrgDti implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5292659725810025137L;
	private DtmAvanceFisfinanOrgDtiId id;

	public DtmAvanceFisfinanOrgDti() {
	}

	public DtmAvanceFisfinanOrgDti(DtmAvanceFisfinanOrgDtiId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codigoOrganismoFinan", column = @Column(name = "CODIGO_ORGANISMO_FINAN", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "nombreOrganismoFinan", column = @Column(name = "NOMBRE_ORGANISMO_FINAN", length = 60)),
			@AttributeOverride(name = "siglasOrganismoFinan", column = @Column(name = "SIGLAS_ORGANISMO_FINAN", length = 20)) })
	public DtmAvanceFisfinanOrgDtiId getId() {
		return this.id;
	}

	public void setId(DtmAvanceFisfinanOrgDtiId id) {
		this.id = id;
	}

}
