package pojoSigade;
// Generated May 16, 2017 12:50:34 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DtmAvanceFisfinanDti generated by hbm2java
 */
@Entity
@Table(name = "DTM_AVANCE_FISFINAN_DTI", schema = "DATAMART")
public class DtmAvanceFisfinanDti implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6382928333615553394L;
	private DtmAvanceFisfinanDtiId id;

	public DtmAvanceFisfinanDti() {
	}

	public DtmAvanceFisfinanDti(DtmAvanceFisfinanDtiId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fechaCorte", column = @Column(name = "FECHA_CORTE", nullable = false, length = 7)),
			@AttributeOverride(name = "noPrestamo", column = @Column(name = "NO_PRESTAMO", nullable = false, length = 60)),
			@AttributeOverride(name = "codigoPresupuestario", column = @Column(name = "CODIGO_PRESUPUESTARIO", nullable = false, length = 15)),
			@AttributeOverride(name = "nombrePrograma", column = @Column(name = "NOMBRE_PROGRAMA", nullable = false, length = 300)),
			@AttributeOverride(name = "codigoOrganismoFinan", column = @Column(name = "CODIGO_ORGANISMO_FINAN", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "siglasOrganismoFinan", column = @Column(name = "SIGLAS_ORGANISMO_FINAN", length = 20)),
			@AttributeOverride(name = "nombreOrganismoFinan", column = @Column(name = "NOMBRE_ORGANISMO_FINAN", length = 60)),
			@AttributeOverride(name = "monedaPrestamo", column = @Column(name = "MONEDA_PRESTAMO", nullable = false, length = 3)),
			@AttributeOverride(name = "montoContratado", column = @Column(name = "MONTO_CONTRATADO", precision = 22, scale = 0)),
			@AttributeOverride(name = "montoContratadoUsd", column = @Column(name = "MONTO_CONTRATADO_USD", precision = 22, scale = 0)),
			@AttributeOverride(name = "montoContratadoGtq", column = @Column(name = "MONTO_CONTRATADO_GTQ", precision = 22, scale = 0)),
			@AttributeOverride(name = "desembolsos", column = @Column(name = "DESEMBOLSOS", precision = 22, scale = 0)),
			@AttributeOverride(name = "desembolsosUsd", column = @Column(name = "DESEMBOLSOS_USD", precision = 22, scale = 0)),
			@AttributeOverride(name = "desembolsosGtq", column = @Column(name = "DESEMBOLSOS_GTQ", precision = 22, scale = 0)),
			@AttributeOverride(name = "fechaDecreto", column = @Column(name = "FECHA_DECRETO", length = 7)),
			@AttributeOverride(name = "fechaSuscripcion", column = @Column(name = "FECHA_SUSCRIPCION", nullable = false, length = 7)),
			@AttributeOverride(name = "fechaVigencia", column = @Column(name = "FECHA_VIGENCIA", nullable = false, length = 7)),
			@AttributeOverride(name = "porDesembolsar", column = @Column(name = "POR_DESEMBOLSAR", precision = 22, scale = 0)),
			@AttributeOverride(name = "porDesembolsarUsd", column = @Column(name = "POR_DESEMBOLSAR_USD", precision = 22, scale = 0)),
			@AttributeOverride(name = "porDesembolsarGtq", column = @Column(name = "POR_DESEMBOLSAR_GTQ", precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoPrestamo", column = @Column(name = "ESTADO_PRESTAMO", length = 4000)) })
	public DtmAvanceFisfinanDtiId getId() {
		return this.id;
	}

	public void setId(DtmAvanceFisfinanDtiId id) {
		this.id = id;
	}

}
