package pojoSigade;
// Generated May 16, 2017 12:50:34 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DtmTiposCambioDti generated by hbm2java
 */
@Entity
@Table(name = "DTM_TIPOS_CAMBIO_DTI", schema = "DATAMART")
public class DtmTiposCambioDti implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8007439335746159302L;
	private DtmTiposCambioDtiId id;

	public DtmTiposCambioDti() {
	}

	public DtmTiposCambioDti(DtmTiposCambioDtiId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fechaTipoCambio", column = @Column(name = "FECHA_TIPO_CAMBIO", nullable = false, length = 7)),
			@AttributeOverride(name = "moneda", column = @Column(name = "MONEDA", nullable = false, length = 3)),
			@AttributeOverride(name = "tipoCambioCompra", column = @Column(name = "TIPO_CAMBIO_COMPRA", nullable = false, precision = 27, scale = 20)),
			@AttributeOverride(name = "tipoCambioVenta", column = @Column(name = "TIPO_CAMBIO_VENTA", nullable = false, precision = 27, scale = 20)) })
	public DtmTiposCambioDtiId getId() {
		return this.id;
	}

	public void setId(DtmTiposCambioDtiId id) {
		this.id = id;
	}

}
