package pojo;
// Generated Jul 28, 2017 12:40:33 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsignacionRaciId generated by hbm2java
 */
@Embeddable
public class AsignacionRaciId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7644712957869101447L;
	private int matrizRaciid;
	private int actividadid;
	private int colaboradorid;
	private String rolRaci;

	public AsignacionRaciId() {
	}

	public AsignacionRaciId(int matrizRaciid, int actividadid, int colaboradorid, String rolRaci) {
		this.matrizRaciid = matrizRaciid;
		this.actividadid = actividadid;
		this.colaboradorid = colaboradorid;
		this.rolRaci = rolRaci;
	}

	@Column(name = "matriz_raciid", nullable = false)
	public int getMatrizRaciid() {
		return this.matrizRaciid;
	}

	public void setMatrizRaciid(int matrizRaciid) {
		this.matrizRaciid = matrizRaciid;
	}

	@Column(name = "actividadid", nullable = false)
	public int getActividadid() {
		return this.actividadid;
	}

	public void setActividadid(int actividadid) {
		this.actividadid = actividadid;
	}

	@Column(name = "colaboradorid", nullable = false)
	public int getColaboradorid() {
		return this.colaboradorid;
	}

	public void setColaboradorid(int colaboradorid) {
		this.colaboradorid = colaboradorid;
	}

	@Column(name = "rol_raci", nullable = false, length = 1)
	public String getRolRaci() {
		return this.rolRaci;
	}

	public void setRolRaci(String rolRaci) {
		this.rolRaci = rolRaci;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsignacionRaciId))
			return false;
		AsignacionRaciId castOther = (AsignacionRaciId) other;

		return (this.getMatrizRaciid() == castOther.getMatrizRaciid())
				&& (this.getActividadid() == castOther.getActividadid())
				&& (this.getColaboradorid() == castOther.getColaboradorid())
				&& ((this.getRolRaci() == castOther.getRolRaci()) || (this.getRolRaci() != null
						&& castOther.getRolRaci() != null && this.getRolRaci().equals(castOther.getRolRaci())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMatrizRaciid();
		result = 37 * result + this.getActividadid();
		result = 37 * result + this.getColaboradorid();
		result = 37 * result + (getRolRaci() == null ? 0 : this.getRolRaci().hashCode());
		return result;
	}

}
