package pojo;
// Generated Jul 28, 2017 12:40:33 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AsignacionRaci generated by hbm2java
 */
@Entity
@Table(name = "asignacion_raci", catalog = "sipro")
public class AsignacionRaci implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5883341467792708981L;
	private AsignacionRaciId id;
	private Actividad actividad;
	private Colaborador colaborador;
	private MatrizRaci matrizRaci;
	private Integer estado;
	private String usuarioCreo;
	private String usuarioActualizo;
	private Date fechaCreacion;
	private Date fechaActualizacion;

	public AsignacionRaci() {
	}

	public AsignacionRaci(AsignacionRaciId id, Actividad actividad, Colaborador colaborador, MatrizRaci matrizRaci) {
		this.id = id;
		this.actividad = actividad;
		this.colaborador = colaborador;
		this.matrizRaci = matrizRaci;
	}

	public AsignacionRaci(AsignacionRaciId id, Actividad actividad, Colaborador colaborador, MatrizRaci matrizRaci,
			Integer estado, String usuarioCreo, String usuarioActualizo, Date fechaCreacion, Date fechaActualizacion) {
		this.id = id;
		this.actividad = actividad;
		this.colaborador = colaborador;
		this.matrizRaci = matrizRaci;
		this.estado = estado;
		this.usuarioCreo = usuarioCreo;
		this.usuarioActualizo = usuarioActualizo;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "matrizRaciid", column = @Column(name = "matriz_raciid", nullable = false)),
			@AttributeOverride(name = "actividadid", column = @Column(name = "actividadid", nullable = false)),
			@AttributeOverride(name = "colaboradorid", column = @Column(name = "colaboradorid", nullable = false)),
			@AttributeOverride(name = "rolRaci", column = @Column(name = "rol_raci", nullable = false, length = 1)) })
	public AsignacionRaciId getId() {
		return this.id;
	}

	public void setId(AsignacionRaciId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actividadid", nullable = false, insertable = false, updatable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorid", nullable = false, insertable = false, updatable = false)
	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matriz_raciid", nullable = false, insertable = false, updatable = false)
	public MatrizRaci getMatrizRaci() {
		return this.matrizRaci;
	}

	public void setMatrizRaci(MatrizRaci matrizRaci) {
		this.matrizRaci = matrizRaci;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creo", length = 30)
	public String getUsuarioCreo() {
		return this.usuarioCreo;
	}

	public void setUsuarioCreo(String usuarioCreo) {
		this.usuarioCreo = usuarioCreo;
	}

	@Column(name = "usuario_actualizo", length = 30)
	public String getUsuarioActualizo() {
		return this.usuarioActualizo;
	}

	public void setUsuarioActualizo(String usuarioActualizo) {
		this.usuarioActualizo = usuarioActualizo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_actualizacion", length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
