package pojo;
// Generated Oct 18, 2017 4:40:30 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComponenteSigade generated by hbm2java
 */
@Entity
@Table(name = "componente_sigade", catalog = "sipro")
public class ComponenteSigade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -478540257208969450L;
	private int id;
	private String nombre;
	private String codigoPresupuestario;
	private int numeroComponente;
	private String montoComponente;
	private int estado;
	private String usuaraioCreo;
	private String usuarioActualizo;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Set<Componente> componentes = new HashSet<Componente>(0);

	public ComponenteSigade() {
	}

	public ComponenteSigade(int id, String nombre, String codigoPresupuestario, int numeroComponente,
			String montoComponente, int estado, String usuaraioCreo, Date fechaCreacion) {
		this.id = id;
		this.nombre = nombre;
		this.codigoPresupuestario = codigoPresupuestario;
		this.numeroComponente = numeroComponente;
		this.montoComponente = montoComponente;
		this.estado = estado;
		this.usuaraioCreo = usuaraioCreo;
		this.fechaCreacion = fechaCreacion;
	}

	public ComponenteSigade(int id, String nombre, String codigoPresupuestario, int numeroComponente,
			String montoComponente, int estado, String usuaraioCreo, String usuarioActualizo, Date fechaCreacion,
			Date fechaActualizacion, Set<Componente> componentes) {
		this.id = id;
		this.nombre = nombre;
		this.codigoPresupuestario = codigoPresupuestario;
		this.numeroComponente = numeroComponente;
		this.montoComponente = montoComponente;
		this.estado = estado;
		this.usuaraioCreo = usuaraioCreo;
		this.usuarioActualizo = usuarioActualizo;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.componentes = componentes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 2000)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo_presupuestario", nullable = false, length = 45)
	public String getCodigoPresupuestario() {
		return this.codigoPresupuestario;
	}

	public void setCodigoPresupuestario(String codigoPresupuestario) {
		this.codigoPresupuestario = codigoPresupuestario;
	}

	@Column(name = "numero_componente", nullable = false)
	public int getNumeroComponente() {
		return this.numeroComponente;
	}

	public void setNumeroComponente(int numeroComponente) {
		this.numeroComponente = numeroComponente;
	}

	@Column(name = "monto_componente", nullable = false, length = 45)
	public String getMontoComponente() {
		return this.montoComponente;
	}

	public void setMontoComponente(String montoComponente) {
		this.montoComponente = montoComponente;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "usuaraio_creo", nullable = false, length = 30)
	public String getUsuaraioCreo() {
		return this.usuaraioCreo;
	}

	public void setUsuaraioCreo(String usuaraioCreo) {
		this.usuaraioCreo = usuaraioCreo;
	}

	@Column(name = "usuario_actualizo", length = 30)
	public String getUsuarioActualizo() {
		return this.usuarioActualizo;
	}

	public void setUsuarioActualizo(String usuarioActualizo) {
		this.usuarioActualizo = usuarioActualizo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_actualizacion", length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "componenteSigade")
	public Set<Componente> getComponentes() {
		return this.componentes;
	}

	public void setComponentes(Set<Componente> componentes) {
		this.componentes = componentes;
	}

}
