package pojo;
// Generated 20/12/2016 11:26:44 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComponentePropiedadValor generated by hbm2java
 */
@Entity
@Table(name = "componente_propiedad_valor", catalog = "sigpro")
public class ComponentePropiedadValor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 390767601180729401L;
	private ComponentePropiedadValorId id;
	private Componente componente;
	private ComponentePropiedad componentePropiedad;

	public ComponentePropiedadValor() {
	}

	public ComponentePropiedadValor(ComponentePropiedadValorId id, Componente componente,
			ComponentePropiedad componentePropiedad) {
		this.id = id;
		this.componente = componente;
		this.componentePropiedad = componentePropiedad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "componenteid", column = @Column(name = "componenteid", nullable = false)),
			@AttributeOverride(name = "componentePropiedadid", column = @Column(name = "componente_propiedadid", nullable = false)),
			@AttributeOverride(name = "valorString", column = @Column(name = "valor_string", length = 4000)),
			@AttributeOverride(name = "valorEntero", column = @Column(name = "valor_entero")),
			@AttributeOverride(name = "valorDecimal", column = @Column(name = "valor_decimal", precision = 15)),
			@AttributeOverride(name = "valorTiempo", column = @Column(name = "valor_tiempo", length = 19)),
			@AttributeOverride(name = "usuarioCreo", column = @Column(name = "usuario_creo", nullable = false, length = 30)),
			@AttributeOverride(name = "usuarioActualizo", column = @Column(name = "usuario_actualizo", length = 30)),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "fecha_creacion", nullable = false, length = 19)),
			@AttributeOverride(name = "fechaActualizacion", column = @Column(name = "fecha_actualizacion", length = 19)) })
	public ComponentePropiedadValorId getId() {
		return this.id;
	}

	public void setId(ComponentePropiedadValorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componenteid", nullable = false, insertable = false, updatable = false)
	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componente_propiedadid", nullable = false, insertable = false, updatable = false)
	public ComponentePropiedad getComponentePropiedad() {
		return this.componentePropiedad;
	}

	public void setComponentePropiedad(ComponentePropiedad componentePropiedad) {
		this.componentePropiedad = componentePropiedad;
	}

}
