package pojo;
// Generated 5/04/2018 04:15:52 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CooperanteId generated by hbm2java
 */
@Embeddable
public class CooperanteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4467357808102521972L;
	private int codigo;
	private int ejercicio;

	public CooperanteId() {
	}

	public CooperanteId(int codigo, int ejercicio) {
		this.codigo = codigo;
		this.ejercicio = ejercicio;
	}

	@Column(name = "codigo", nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "ejercicio", nullable = false)
	public int getEjercicio() {
		return this.ejercicio;
	}

	public void setEjercicio(int ejercicio) {
		this.ejercicio = ejercicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CooperanteId))
			return false;
		CooperanteId castOther = (CooperanteId) other;

		return (this.getCodigo() == castOther.getCodigo()) && (this.getEjercicio() == castOther.getEjercicio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigo();
		result = 37 * result + this.getEjercicio();
		return result;
	}

}
