package pojo;
// Generated Dec 5, 2016 7:40:54 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name = "entidad", catalog = "sigpro")
public class Entidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8817581293638378973L;
	private Integer entidad;
	private String nombre;
	private Set<UnidadEjecutora> unidadEjecutoras = new HashSet<UnidadEjecutora>(0);

	public Entidad() {
	}

	public Entidad(String nombre) {
		this.nombre = nombre;
	}

	public Entidad(String nombre, Set<UnidadEjecutora> unidadEjecutoras) {
		this.nombre = nombre;
		this.unidadEjecutoras = unidadEjecutoras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entidad", unique = true, nullable = false)
	public Integer getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Integer entidad) {
		this.entidad = entidad;
	}

	@Column(name = "nombre", nullable = false, length = 1000)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<UnidadEjecutora> getUnidadEjecutoras() {
		return this.unidadEjecutoras;
	}

	public void setUnidadEjecutoras(Set<UnidadEjecutora> unidadEjecutoras) {
		this.unidadEjecutoras = unidadEjecutoras;
	}

}
