package pojo;
// Generated 20/12/2016 11:26:44 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Estadotabla generated by hbm2java
 */
@Entity
@Table(name = "estadotabla", catalog = "sigpro")
public class Estadotabla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8213213344413568194L;
	private EstadotablaId id;
	private String estado;

	public Estadotabla() {
	}

	public Estadotabla(EstadotablaId id, String estado) {
		this.id = id;
		this.estado = estado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false, length = 100)),
			@AttributeOverride(name = "tabla", column = @Column(name = "tabla", nullable = false, length = 100)) })
	public EstadotablaId getId() {
		return this.id;
	}

	public void setId(EstadotablaId id) {
		this.id = id;
	}

	@Column(name = "estado", nullable = false, length = 4000)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
