package pojo;
<<<<<<< HEAD
// Generated 27/07/2017 10:30:52 AM by Hibernate Tools 5.2.3.Final
=======
// Generated Jul 28, 2017 12:40:33 AM by Hibernate Tools 5.2.3.Final
>>>>>>> master

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EstructuraArbol generated by hbm2java
 */
@Entity
@Table(name = "estructura_arbol", catalog = "sipro")
public class EstructuraArbol implements java.io.Serializable {

<<<<<<< HEAD
=======
	/**
	 * 
	 */
	private static final long serialVersionUID = -6105607288540664425L;
>>>>>>> master
	private EstructuraArbolId id;

	public EstructuraArbol() {
	}

	public EstructuraArbol(EstructuraArbolId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "prestamo", column = @Column(name = "prestamo")),
			@AttributeOverride(name = "componente", column = @Column(name = "componente")),
			@AttributeOverride(name = "producto", column = @Column(name = "producto")),
			@AttributeOverride(name = "subproducto", column = @Column(name = "subproducto")),
			@AttributeOverride(name = "actividad", column = @Column(name = "actividad")),
			@AttributeOverride(name = "treelevel", column = @Column(name = "treelevel")),
			@AttributeOverride(name = "treepath", column = @Column(name = "treepath", length = 511)),
			@AttributeOverride(name = "fechaInicio", column = @Column(name = "fecha_inicio", length = 19)) })
	public EstructuraArbolId getId() {
		return this.id;
	}

	public void setId(EstructuraArbolId id) {
		this.id = id;
	}

}
