package pojo;
// Generated 20/12/2016 11:26:44 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FormularioItemValor generated by hbm2java
 */
@Entity
@Table(name = "formulario_item_valor", catalog = "sigpro")
public class FormularioItemValor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5149552643888478166L;
	private FormularioItemValorId id;
	private Componente componente;
	private FormularioItem formularioItem;
	private Producto producto;
	private Proyecto proyecto;

	public FormularioItemValor() {
	}

	public FormularioItemValor(FormularioItemValorId id, Componente componente, FormularioItem formularioItem,
			Producto producto, Proyecto proyecto) {
		this.id = id;
		this.componente = componente;
		this.formularioItem = formularioItem;
		this.producto = producto;
		this.proyecto = proyecto;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "formularioItemid", column = @Column(name = "formulario_itemid", nullable = false)),
			@AttributeOverride(name = "valorEntero", column = @Column(name = "valor_entero", nullable = false)),
			@AttributeOverride(name = "valorString", column = @Column(name = "valor_string", length = 4000)),
			@AttributeOverride(name = "valorTiempo", column = @Column(name = "valor_tiempo", length = 19)),
			@AttributeOverride(name = "valorDecimal", column = @Column(name = "valor_decimal", precision = 15)),
			@AttributeOverride(name = "proyectoid", column = @Column(name = "proyectoid", nullable = false)),
			@AttributeOverride(name = "componenteid", column = @Column(name = "componenteid", nullable = false)),
			@AttributeOverride(name = "productoid", column = @Column(name = "productoid", nullable = false)),
			@AttributeOverride(name = "usuarioCreo", column = @Column(name = "usuario_creo", nullable = false, length = 30)),
			@AttributeOverride(name = "usuarioActualizo", column = @Column(name = "usuario_actualizo", length = 30)),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "fecha_creacion", nullable = false, length = 19)),
			@AttributeOverride(name = "fechaActualizacion", column = @Column(name = "fecha_actualizacion", length = 19)) })
	public FormularioItemValorId getId() {
		return this.id;
	}

	public void setId(FormularioItemValorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componenteid", nullable = false, insertable = false, updatable = false)
	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "formulario_itemid", nullable = false, insertable = false, updatable = false)
	public FormularioItem getFormularioItem() {
		return this.formularioItem;
	}

	public void setFormularioItem(FormularioItem formularioItem) {
		this.formularioItem = formularioItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productoid", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proyectoid", nullable = false, insertable = false, updatable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

}
