package pojo;
// Generated Jul 13, 2017 10:05:07 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MvEpEstructura generated by hbm2java
 */
@Entity
@Table(name = "mv_ep_estructura", catalog = "sipro")
public class MvEpEstructura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3992423520345251641L;
	private MvEpEstructuraId id;

	public MvEpEstructura() {
	}

	public MvEpEstructura(MvEpEstructuraId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ejercicio", column = @Column(name = "ejercicio")),
			@AttributeOverride(name = "fuente", column = @Column(name = "fuente")),
			@AttributeOverride(name = "organismo", column = @Column(name = "organismo")),
			@AttributeOverride(name = "correlativo", column = @Column(name = "correlativo")),
			@AttributeOverride(name = "programa", column = @Column(name = "programa")),
			@AttributeOverride(name = "subprograma", column = @Column(name = "subprograma")),
			@AttributeOverride(name = "proyecto", column = @Column(name = "proyecto")),
			@AttributeOverride(name = "actividad", column = @Column(name = "actividad")),
			@AttributeOverride(name = "obra", column = @Column(name = "obra")),
			@AttributeOverride(name = "mes1r", column = @Column(name = "mes1r", precision = 59)),
			@AttributeOverride(name = "mes2r", column = @Column(name = "mes2r", precision = 59)),
			@AttributeOverride(name = "mes3r", column = @Column(name = "mes3r", precision = 59)),
			@AttributeOverride(name = "mes4r", column = @Column(name = "mes4r", precision = 59)),
			@AttributeOverride(name = "mes5r", column = @Column(name = "mes5r", precision = 59)),
			@AttributeOverride(name = "mes6r", column = @Column(name = "mes6r", precision = 59)),
			@AttributeOverride(name = "mes7r", column = @Column(name = "mes7r", precision = 59)),
			@AttributeOverride(name = "mes8r", column = @Column(name = "mes8r", precision = 59)),
			@AttributeOverride(name = "mes9r", column = @Column(name = "mes9r", precision = 59)),
			@AttributeOverride(name = "mes10r", column = @Column(name = "mes10r", precision = 59)),
			@AttributeOverride(name = "mes11r", column = @Column(name = "mes11r", precision = 59)),
			@AttributeOverride(name = "mes12r", column = @Column(name = "mes12r", precision = 59)) })
	public MvEpEstructuraId getId() {
		return this.id;
	}

	public void setId(MvEpEstructuraId id) {
		this.id = id;
	}

}
