package pojo;
// Generated 20/12/2016 11:26:44 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObjetoFormulario generated by hbm2java
 */
@Entity
@Table(name = "objeto_formulario", catalog = "sigpro")
public class ObjetoFormulario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1849078949317284926L;
	private ObjetoFormularioId id;
	private Componente componente;
	private Formulario formulario;
	private FormularioTipo formularioTipo;
	private Producto producto;
	private Proyecto proyecto;
	private String usuarioCreo;
	private String usuarioActualizo;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private int estado;

	public ObjetoFormulario() {
	}

	public ObjetoFormulario(ObjetoFormularioId id, Formulario formulario, FormularioTipo formularioTipo,
			String usuarioCreo, Date fechaCreacion, int estado) {
		this.id = id;
		this.formulario = formulario;
		this.formularioTipo = formularioTipo;
		this.usuarioCreo = usuarioCreo;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
	}

	public ObjetoFormulario(ObjetoFormularioId id, Componente componente, Formulario formulario,
			FormularioTipo formularioTipo, Producto producto, Proyecto proyecto, String usuarioCreo,
			String usuarioActualizo, Date fechaCreacion, Date fechaActualizacion, int estado) {
		this.id = id;
		this.componente = componente;
		this.formulario = formulario;
		this.formularioTipo = formularioTipo;
		this.producto = producto;
		this.proyecto = proyecto;
		this.usuarioCreo = usuarioCreo;
		this.usuarioActualizo = usuarioActualizo;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.estado = estado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "formularioid", column = @Column(name = "formularioid", nullable = false)),
			@AttributeOverride(name = "objetoTipoid", column = @Column(name = "objeto_tipoid", nullable = false)) })
	public ObjetoFormularioId getId() {
		return this.id;
	}

	public void setId(ObjetoFormularioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componenteid")
	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "formularioid", nullable = false, insertable = false, updatable = false)
	public Formulario getFormulario() {
		return this.formulario;
	}

	public void setFormulario(Formulario formulario) {
		this.formulario = formulario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "objeto_tipoid", nullable = false, insertable = false, updatable = false)
	public FormularioTipo getFormularioTipo() {
		return this.formularioTipo;
	}

	public void setFormularioTipo(FormularioTipo formularioTipo) {
		this.formularioTipo = formularioTipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productoid")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proyectoid")
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "usuario_creo", nullable = false, length = 30)
	public String getUsuarioCreo() {
		return this.usuarioCreo;
	}

	public void setUsuarioCreo(String usuarioCreo) {
		this.usuarioCreo = usuarioCreo;
	}

	@Column(name = "usuario_actualizo", length = 30)
	public String getUsuarioActualizo() {
		return this.usuarioActualizo;
	}

	public void setUsuarioActualizo(String usuarioActualizo) {
		this.usuarioActualizo = usuarioActualizo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_actualizacion", length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

}
