package pojo;
// Generated Jan 27, 2017 10:39:58 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjetoActividadId generated by hbm2java
 */
@Embeddable
public class ObjetoActividadId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3302208475776030530L;
	private int actividadid;
	private int objetoId;
	private int objetoTipo;

	public ObjetoActividadId() {
	}

	public ObjetoActividadId(int actividadid, int objetoId, int objetoTipo) {
		this.actividadid = actividadid;
		this.objetoId = objetoId;
		this.objetoTipo = objetoTipo;
	}

	@Column(name = "actividadid", nullable = false)
	public int getActividadid() {
		return this.actividadid;
	}

	public void setActividadid(int actividadid) {
		this.actividadid = actividadid;
	}

	@Column(name = "objeto_id", nullable = false)
	public int getObjetoId() {
		return this.objetoId;
	}

	public void setObjetoId(int objetoId) {
		this.objetoId = objetoId;
	}

	@Column(name = "objeto_tipo", nullable = false)
	public int getObjetoTipo() {
		return this.objetoTipo;
	}

	public void setObjetoTipo(int objetoTipo) {
		this.objetoTipo = objetoTipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjetoActividadId))
			return false;
		ObjetoActividadId castOther = (ObjetoActividadId) other;

		return (this.getActividadid() == castOther.getActividadid()) && (this.getObjetoId() == castOther.getObjetoId())
				&& (this.getObjetoTipo() == castOther.getObjetoTipo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActividadid();
		result = 37 * result + this.getObjetoId();
		result = 37 * result + this.getObjetoTipo();
		return result;
	}

}
