package pojo;
// Generated 20/12/2016 11:26:44 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObjetoRiesgo generated by hbm2java
 */
@Entity
@Table(name = "objeto_riesgo", catalog = "sigpro")
public class ObjetoRiesgo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2852499796948077793L;
	private ObjetoRiesgoId id;
	private Componente componente;
	private Producto producto;
	private Proyecto proyecto;
	private Riesgo riesgo;

	public ObjetoRiesgo() {
	}

	public ObjetoRiesgo(ObjetoRiesgoId id, Componente componente, Producto producto, Proyecto proyecto, Riesgo riesgo) {
		this.id = id;
		this.componente = componente;
		this.producto = producto;
		this.proyecto = proyecto;
		this.riesgo = riesgo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "riesgoid", column = @Column(name = "riesgoid", nullable = false)),
			@AttributeOverride(name = "proyectoid", column = @Column(name = "proyectoid", nullable = false)),
			@AttributeOverride(name = "componenteid", column = @Column(name = "componenteid", nullable = false)),
			@AttributeOverride(name = "productoid", column = @Column(name = "productoid", nullable = false)),
			@AttributeOverride(name = "usuarioCreo", column = @Column(name = "usuario_creo", nullable = false, length = 30)),
			@AttributeOverride(name = "usuarioActualizo", column = @Column(name = "usuario_actualizo", length = 30)),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "fecha_creacion", nullable = false, length = 19)),
			@AttributeOverride(name = "fechaActualizacion", column = @Column(name = "fecha_actualizacion", length = 19)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado", nullable = false)) })
	public ObjetoRiesgoId getId() {
		return this.id;
	}

	public void setId(ObjetoRiesgoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componenteid", nullable = false, insertable = false, updatable = false)
	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productoid", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proyectoid", nullable = false, insertable = false, updatable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "riesgoid", nullable = false, insertable = false, updatable = false)
	public Riesgo getRiesgo() {
		return this.riesgo;
	}

	public void setRiesgo(Riesgo riesgo) {
		this.riesgo = riesgo;
	}

}
