package pojo;
// Generated Oct 20, 2017 7:34:40 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrestamoTipoPrestamo generated by hbm2java
 */
@Entity
@Table(name = "prestamo_tipo_prestamo", catalog = "sipro")
public class PrestamoTipoPrestamo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1162663740885265093L;
	private PrestamoTipoPrestamoId id;
	private Prestamo prestamo;
	private PrestamoTipo prestamoTipo;

	public PrestamoTipoPrestamo() {
	}

	public PrestamoTipoPrestamo(PrestamoTipoPrestamoId id, Prestamo prestamo, PrestamoTipo prestamoTipo) {
		this.id = id;
		this.prestamo = prestamo;
		this.prestamoTipo = prestamoTipo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prestamoId", column = @Column(name = "prestamoId", nullable = false)),
			@AttributeOverride(name = "tipoPrestamoId", column = @Column(name = "tipoPrestamoId", nullable = false)),
			@AttributeOverride(name = "usuarioCreo", column = @Column(name = "usuario_creo", nullable = false, length = 30)),
			@AttributeOverride(name = "usuarioActualizo", column = @Column(name = "usuario_actualizo", length = 30)),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "fecha_creacion", nullable = false, length = 19)),
			@AttributeOverride(name = "fechaActualizacion", column = @Column(name = "fecha_actualizacion", length = 19)) })
	public PrestamoTipoPrestamoId getId() {
		return this.id;
	}

	public void setId(PrestamoTipoPrestamoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prestamoId", nullable = false, insertable = false, updatable = false)
	public Prestamo getPrestamo() {
		return this.prestamo;
	}

	public void setPrestamo(Prestamo prestamo) {
		this.prestamo = prestamo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipoPrestamoId", nullable = false, insertable = false, updatable = false)
	public PrestamoTipo getPrestamoTipo() {
		return this.prestamoTipo;
	}

	public void setPrestamoTipo(PrestamoTipo prestamoTipo) {
		this.prestamoTipo = prestamoTipo;
	}

}
