package pojo;
// Generated Dec 5, 2016 7:40:54 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoPropiedadValor generated by hbm2java
 */
@Entity
@Table(name = "producto_propiedad_valor", catalog = "sigpro")
public class ProductoPropiedadValor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6185958159806007904L;
	private ProductoPropiedadValorId id;
	private Producto producto;
	private ProductoPropiedad productoPropiedad;

	public ProductoPropiedadValor() {
	}

	public ProductoPropiedadValor(ProductoPropiedadValorId id, Producto producto, ProductoPropiedad productoPropiedad) {
		this.id = id;
		this.producto = producto;
		this.productoPropiedad = productoPropiedad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productoPropiedadid", column = @Column(name = "producto_propiedadid", nullable = false)),
			@AttributeOverride(name = "productoid", column = @Column(name = "productoid", nullable = false)),
			@AttributeOverride(name = "valorEntero", column = @Column(name = "valor_entero")),
			@AttributeOverride(name = "valorString", column = @Column(name = "valor_string", length = 4000)),
			@AttributeOverride(name = "valorDecimal", column = @Column(name = "valor_decimal", precision = 15)),
			@AttributeOverride(name = "valorTiempo", column = @Column(name = "valor_tiempo", length = 19)),
			@AttributeOverride(name = "usuarioCreo", column = @Column(name = "usuario_creo", nullable = false, length = 30)),
			@AttributeOverride(name = "usuarioActualizo", column = @Column(name = "usuario_actualizo", length = 30)),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "fecha_creacion", nullable = false, length = 19)),
			@AttributeOverride(name = "fechaActualizacion", column = @Column(name = "fecha_actualizacion", length = 19)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado")) })
	public ProductoPropiedadValorId getId() {
		return this.id;
	}

	public void setId(ProductoPropiedadValorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productoid", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto_propiedadid", nullable = false, insertable = false, updatable = false)
	public ProductoPropiedad getProductoPropiedad() {
		return this.productoPropiedad;
	}

	public void setProductoPropiedad(ProductoPropiedad productoPropiedad) {
		this.productoPropiedad = productoPropiedad;
	}

}
