package pojo;
// Generated 27/02/2017 11:04:39 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProgramaProyectoId generated by hbm2java
 */
@Embeddable
public class ProgramaProyectoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int programaid;
	private int proyectoid;

	public ProgramaProyectoId() {
	}

	public ProgramaProyectoId(int programaid, int proyectoid) {
		this.programaid = programaid;
		this.proyectoid = proyectoid;
	}

	@Column(name = "programaid", nullable = false)
	public int getProgramaid() {
		return this.programaid;
	}

	public void setProgramaid(int programaid) {
		this.programaid = programaid;
	}

	@Column(name = "proyectoid", nullable = false)
	public int getProyectoid() {
		return this.proyectoid;
	}

	public void setProyectoid(int proyectoid) {
		this.proyectoid = proyectoid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProgramaProyectoId))
			return false;
		ProgramaProyectoId castOther = (ProgramaProyectoId) other;

		return (this.getProgramaid() == castOther.getProgramaid())
				&& (this.getProyectoid() == castOther.getProyectoid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProgramaid();
		result = 37 * result + this.getProyectoid();
		return result;
	}

}
