package pojo;
// Generated 20/12/2016 11:26:44 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProyectoPropiedadCatalogo generated by hbm2java
 */
@Entity
@Table(name = "proyecto_propiedad_catalogo", catalog = "sigpro")
public class ProyectoPropiedadCatalogo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4300619206213513464L;
	private ProyectoPropiedadCatalogoId id;
	private ProyectoPropiedad proyectoPropiedad;

	public ProyectoPropiedadCatalogo() {
	}

	public ProyectoPropiedadCatalogo(ProyectoPropiedadCatalogoId id, ProyectoPropiedad proyectoPropiedad) {
		this.id = id;
		this.proyectoPropiedad = proyectoPropiedad;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 200)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", length = 1000)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado")),
			@AttributeOverride(name = "usuarioCreo", column = @Column(name = "usuario_creo", length = 30)),
			@AttributeOverride(name = "usuarioActualizo", column = @Column(name = "usuario_actualizo", length = 30)),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "fecha_creacion", length = 19)),
			@AttributeOverride(name = "fechaActualizacion", column = @Column(name = "fecha_actualizacion", length = 19)),
			@AttributeOverride(name = "proyectoPropiedadid", column = @Column(name = "proyecto_propiedadid", nullable = false)) })
	public ProyectoPropiedadCatalogoId getId() {
		return this.id;
	}

	public void setId(ProyectoPropiedadCatalogoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proyecto_propiedadid", nullable = false, insertable = false, updatable = false)
	public ProyectoPropiedad getProyectoPropiedad() {
		return this.proyectoPropiedad;
	}

	public void setProyectoPropiedad(ProyectoPropiedad proyectoPropiedad) {
		this.proyectoPropiedad = proyectoPropiedad;
	}

}
