package pojo;
// Generated May 2, 2017 11:16:34 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ptipopropiedad generated by hbm2java
 */
@Entity
@Table(name = "ptipopropiedad", catalog = "sipro")
public class Ptipopropiedad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9066874930639039444L;
	private PtipopropiedadId id;

	public Ptipopropiedad() {
	}

	public Ptipopropiedad(PtipopropiedadId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productoTipoid", column = @Column(name = "producto_tipoid", nullable = false)),
			@AttributeOverride(name = "productoPropiedadid", column = @Column(name = "producto_propiedadid", nullable = false)) })
	public PtipopropiedadId getId() {
		return this.id;
	}

	public void setId(PtipopropiedadId id) {
		this.id = id;
	}

}
