package pojo;
// Generated 16/12/2016 03:14:50 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuariolog generated by hbm2java
 */
@Entity
@Table(name = "usuariolog", catalog = "sigpro")
public class Usuariolog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1163268594466555337L;
	private String usuario;
	private Date fecha;

	public Usuariolog() {
	}

	public Usuariolog(String usuario, Date fecha) {
		this.usuario = usuario;
		this.fecha = fecha;
	}

	@Id

	@Column(name = "usuario", unique = true, nullable = false, length = 32)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
