package pojo;
// Generated Feb 3, 2017 9:12:33 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsuarioLog generated by hbm2java
 */
@Entity
@Table(name = "usuario_log", catalog = "sigpro")
public class UsuarioLog implements java.io.Serializable {

	private UsuarioLogId id;

	public UsuarioLog() {
	}

	public UsuarioLog(UsuarioLogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "usuario", column = @Column(name = "usuario", length = 30)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 19)) })
	public UsuarioLogId getId() {
		return this.id;
	}

	public void setId(UsuarioLogId id) {
		this.id = id;
	}

}
